### ISSUE TITLE
[BUG] pain.001.001.02 GrpHdr fields order

### ISSUE THREAD

**Issue by adrien-may** [jerebtw/Sepa-JS-XML#186]
The generated document seems to have fields ordered in a wrong way within `GrpHdr`

For pain.001.001.02 (the only I tried), it is supposed to be in this order :

MsgId
CreDtTm
BtchBookg
NbOfTxs
CtrlSum
Grpg
InitgPty

What your library does right now: 

1 - create this basis:

MsgId
CreDtTm
NbOfTxs
CtrlSum
InitgPty

2 - if version is pain.001.001.02, append
BtchBookg and Grpg 

I'm not submitting a PR because I fear there is more to update to have a correct behavior.

**Comment by jerebtw** [comment]
Thanks for the report, I will look at it
