### ISSUE TITLE
[BUG] pain.001.001.02 pmtInfData should not contained BtchBookg NbOfTxs and CtrlSum

### ISSUE THREAD

**Issue by adrien-may** [jerebtw/Sepa-JS-XML#188]
Those fields get an "undefined" value but end up in the xml file like this : <BtchBook /><NbOfTxs /><CtrlSum />
This does not seem to comply with the specification.

**Comment by jerebtw** [comment]
If you like, you can make a pr

**Comment by jerebtw** [comment]
#192
