### ISSUE TITLE
[BUG] Debtor BIC is not optional

### ISSUE THREAD

**Issue by dreinon** [jerebtw/Sepa-JS-XML#287]
In the 008.001.002 and later specification, debtor BIC is optional, and only needed "when the Creditor Bank explicitly requests the BIC of the Debtor Bank whereby at least one of the two Banks is located in a non-EEA SEPA country or territory". [Link to specification, Page 19, #2.40](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC130-08%20SDD%20Core%20C2B%20IG%202017%20V1.0.pdf).

When bic is not provided DbtrAgt tag has to be the following:
```xml
<DbtrAgt>
    <FinInstnId/>
</DbtrAgt>
```

Do you think this could be implemented? Thanks in advance!

**Comment by jerebtw** [comment]
If I understand correctly, pain.008.001.02 and pain.008.003.02 are under these specifications, right?

**Comment by jerebtw** [comment]
Do you have a small test case for testing (with fake data) the fix?

**Comment by dreinon** [comment]
Sorry, I just checked that the node I wrote in the issue was not the one I needed, but it seems to also be optional. The one I need, which is also optional in the specification, is on page 31, #2.129.

Thanks!

**Comment by jerebtw** [comment]
Please try [3.0.7-beta.1](https://www.npmjs.com/package/sepa-js-xml/v/3.0.7-beta.1) and let me know if it solves your problem.

**Comment by jerebtw** [comment]
@dreinon

**Comment by dreinon** [comment]
SFLR, I haven't tried it but looking at the code, the fact that bic is not optional inside the Payment type makes me think it won't solve my problem. As I mentioned in my last comment, I asked for the wrong type to be optional, which finally ended being able to be optional as well by the SEPA schema specification, so the work was not in vain, but the one field I need to be optional is the bic of the debtor, inside the Payment type. Thanks in advance!

**Comment by dreinon** [comment]
@jerebtw

**Comment by jerebtw** [comment]
@dreinon can you look 3.0.8-beta.1

**Comment by jerebtw** [comment]
Version 3.1.0 has been released and should fix this problem
